services:
  - type: web
    name: openwebui-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: openwebui-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: openwebui-redis
          property: connectionString
      - key: WEBUI_SECRET_KEY
        generateValue: true
      - key: ENABLE_SIGNUP
        value: "true"
      - key: ENABLE_LOGIN_FORM
        value: "true"
      - key: ENABLE_OLLAMA_API
        value: "true"
      - key: ENABLE_OPENAI_API
        value: "true"
      - key: ENABLE_DIRECT_CONNECTIONS
        value: "true"
      - key: ENABLE_IMAGE_GENERATION
        value: "true"
      - key: ENABLE_CODE_EXECUTION
        value: "false"
      - key: ENABLE_CODE_INTERPRETER
        value: "false"
      - key: WEBUI_AUTH
        value: "true"
      - key: WEBUI_NAME
        value: "OpenWebUI"
      - key: WEBUI_URL
        value: "https://your-frontend-domain.vercel.app"
      - key: CORS_ORIGINS
        value: "https://your-frontend-domain.vercel.app"

databases:
  - name: openwebui-db
    databaseName: openwebui
    user: openwebui
    plan: starter

services:
  - type: redis
    name: openwebui-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
